### ISSUE TITLE
String Calculator ignores 1001!

### ISSUE THREAD

**Issue by batkot** [tpamula/StringCalculatorKata#1]
Test says it should ignore numbers bigger than 1001 ( https://github.com/tpamula/StringCalculatorKata/blob/master/StringCalculatorKata.Tests/StringCalculatorTests.cs )

``` C#
        public void ignores_numbers_bigger_than_1001(string input, int expected)
        {
            var calculator = new StringCalculator();

            int result = calculator.Add(input);

            Assert.Equal(expected, result);
        }
```

However, it also ignores 1001! It's really misleading and caused a lot of damage on our production servers :/

**Comment by tpamula** [comment]
Though the title was technically correct (the best kind of correct) it was improved not to be misleading due to your suggestion. Thank you for feedback.
